receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4319" # Porta para OTLP via HTTP
      grpc:
        endpoint: "0.0.0.0:4317" # Porta para OTLP via gRPC

processors:
  batch:
    timeout: 5s
    send_batch_size: 512
  memory_limiter:
    limit_mib: 400
    spike_limit_mib: 100
    check_interval: 1s

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: "http://localhost:14268/api/traces"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [logging, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [logging]