receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4319" # Porta para OTLP via HTTP
      grpc:
        endpoint: "0.0.0.0:4317" # Porta para OTLP via gRPC

processors:
  batch: # Agrupamento de spans para eficiência
    timeout: 5s
    send_batch_size: 512

exporters:
  logging: # Exportar spans para logs no console
    loglevel: debug
  jaeger: # Exportar para Jaeger para visualização
    endpoint: "http://localhost:14268/api/traces"

service:
  pipelines:
    traces:
      receivers: [otlp]       # Receber spans via OTLP
      processors: [batch]     # Processar spans em lote
      exporters: [logging, jaeger] # Exportar para logs e Jaeger
